micronaut:
  application:
    name: my-application
  data:
    datasource:
      default:
        url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: ''
        schema-generate: CREATE_DROP # Generate schema for testing
        dialect: H2
    jpa:
      enabled: false
