micronaut:
  application:
    name: Postgres-Application

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    password: mypassword
    url: jdbc:postgresql://localhost:5432/micronautbox
    username: myuser
    driver-class-name: org.postgresql.Driver
    schema-generate: CREATE

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true