name: Build and Test

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: micronautbox
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradlew Permissions
        run: chmod +x ./gradlew

      - name: Ensure Gradle Wrapper
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi

      - name: Run Pipeline
        run: make pipeline